services:
  mongo:
    container_name: workshopmongo-mongodb
    image: 'mongo'
    volumes:
      - mongodb-data:/data/db
    ports:
      - '27017:27017'
    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: workshop_mongo

volumes:
  mongodb-data: